### ISSUE TITLE
convert tests from ava to jest

### ISSUE THREAD

**Issue by vimark1** [vimark1/seleniumjs#8]

**Comment by konsvasi** [comment]
I'll take a look into it.

**Comment by vimark1** [comment]
Awesome @konsvasi

**Comment by konsvasi** [comment]
Can you take a look at my [commit](https://github.com/konsvasi/seleniumjs/commit/115ee139a97070423dc6456deeed943603184d45). The tests seem to be passing except the ones that use the `require-dir` package. During the tests the `zombieFunctions` has an empty object instead of the functions that are in the folders. I've checked the path and it seems to be correct, I didn't change it.

**Comment by vimark1** [comment]
Having a look now

**Comment by vimark1** [comment]
Hey @konsvasi - it seems to be a bug in jest that won't get fixed see https://github.com/aseemk/requireDir/issues/53 - the solution there was to use `require-directory`. Let me know if that helps.  Thanks!

**Comment by konsvasi** [comment]
Ok, I'll try it, thanks.

**Comment by vimark1** [comment]
Merged in #10
